apiVersion: batch/v1
kind: Job
metadata:
  name: kedro-training-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kedro
        image: kedro-pipeline:latest
        volumeMounts:
        - mountPath: /data
          name: model-storage
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc